server:
  port: 8080

spring:
  application:
    name: vitbon-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vitbon}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.vitbon: DEBUG
    org.springframework: INFO
